language: java
jdk:
- oraclejdk8
script:
- mvn test
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.login=$SONAR_TOKEN
addons:
  sonarqube: true
  apt:
    packages:
    - oracle-java8-installer
env:
  global:
    secure: nQg0USO2k7UfKhldTVv2ZrKWiG0lNvTY6F7DLvUjKuyHzoxjAcBT4nV1TDKZNZpzQuMh+LuyCvnSnrC21F7iEbUeE/vnLCtVmRpPDkvP6fS9bPD2JxYsyL+mX0ify1otppW/FcdQ1aq/CCpVuMr79Xg4woZNijacL7U4IGmi/rrCtQi5TXnHF8E7vm2Yal7RRhCPd5AVk3em85weYms+9GEEAKZu1ovgvb8A5+469CchtHhIMeAd0BR9GtfiuSV9hcoYVdXvMob+l+xB5kfSWmVGMlAXElu0m9tDW7IwLcG8G9hwFrN/Bznrw7227X7f6I5RtwIxGQuOobdq6h41zqmiXyfmNYftdL3RHK44OAPCxRHiDCyucPf1SmKL3fsrht6cSgT2WeE5sTf4bhVwUoljSbrwQb8iK3Nn+k8kRIb2LsrXOLyEZM9M2XYtQgVk5RhY46q2OLZb79zsUORk+kqyvMB5P5YmmBr6flAVCHQAH4eX1J6O6dCCGplJ0qS2cmi1H2sjPciiTc6qV60NCAB3dIqsHrk32H6ZMnbfrLLT4PEUHB5ynk0YP1/MzL9swS2jfBOMuru3osGwLCmgGRLvahpHkgPu02coKBDlfhoJ4vmeh18K0pIJ76qYfjUnqD772vMvlKjhlowr2/azsUcSgtN/M3ZGLA5qGoPDP9Y=
